# Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.daemon=true

# ????????? ????-???????? JDK
org.gradle.java.installations.auto-download=false

# ??????? JDK 17 (????????? ???? ???? ?????)
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64

# Android settings
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official